version: '1.0'

services:
  parser:
    build: ./parser
    image: parser-image:latest
    container_name: parser
    ports:
      - "8084:8084"
    depends_on:
      - restservice

  restservice:
    build: ./restservice
    image: restservice-image:latest
    container_name: restservice
    ports:
      - "8085:8085"
    depends_on:
      - baggins

  bot:
    build: ./bot
    image: bot-image:latest
    container_name: bot
    ports:
      - "8082:8082"
    depends_on:
      - parser

  baggins:
    build: ./baggins
    image: baggins-image:latest
    container_name: baggins
    ports:
      - "8083:8083"
    depends_on:
      - marketplace-db

  marketplace-db:
    container_name: marketplace-db
    image: postgres:15
    environment: # todo change env
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
      POSTGRES_DB: marketplace
      PGDATA: /data/postgres
    volumes:
      - baggins-postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - marketplace-db
    command:
      - --hub-mode=off
      - --changelog-file=master.yaml
      - --driver=org.postgresql.Driver # todo change env
      - --url=jdbc:postgresql://marketplace-db:5432/marketplace
      - --username=marketplace
      - --password=marketplace
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  baggins-postgres:
    { }
  prometheus:
    { }
  grafana:
    { }