# todo add ports for modules
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'baggins'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]

  - job_name: 'restservice'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]

  - job_name: 'parser'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]

  - job_name: 'bot'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]