--liquibase formatted sql

--changeset  sleepwalker:create_products_table
CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID          BIGINT UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TITLE       VARCHAR(255)                                               NOT NULL,
    DESCRIPTION varchar(2040)                                              NOT NULL,
    PRICE       BIGINT                                                     NOT NULL
);
