--liquibase formatted sql

--changeset  sleepwalker:create_customers_products_table
CREATE TABLE IF NOT EXISTS CUSTOMERS_PRODUCTS
(
    CUSTOMER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CONSTRAINT FK_CUSTOMERS_PRODUCTS_CUSTOMERS_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS,
    CONSTRAINT FK_CUSTOMERS_PRODUCTS_PRODUCTS_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS,
    CONSTRAINT PK_CUSTOMERS_PRODUCTS PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID)
);
