--liquibase formatted sql

--changeset  sleepwalker:create_images_table
CREATE TABLE IF NOT EXISTS IMAGES
(
    ID         BIGINT UNIQUE PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TITLE      VARCHAR(255)                                               NOT NULL,
    CONTENT    BYTEA                                                      not null,
    PRODUCT_ID BIGINT                                                     not null,
    constraint fk_images_product foreign key (PRODUCT_ID) references PRODUCTS
);
